### ISSUE TITLE
"getServerInfo" gives an 404 error?

### ISSUE THREAD

**Issue by jakubiakdev** [Heavenston/FiveM-Api#4]
My code: 
```
fivem.getServerInfo("ip").then((server)  =>  console.log(server.players.length));
```
(copied from example)
after running it i get an output:
```
undefined:1
404 page not found
    ^

SyntaxError: Unexpected token p in JSON at position 4
    at JSON.parse (<anonymous>)
    at Request._callback (/home/jakubiak/dev/discord-bot/node_modules/fivem-api/index.js:11:24)
    at Request.self.callback (/home/jakubiak/dev/discord-bot/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/home/jakubiak/dev/discord-bot/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (/home/jakubiak/dev/discord-bot/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1223:12)
```

**Comment by crispyaus** [comment]
you need to set ip to your server ip + port 30120 or whatever port you have selected.

**Comment by LouisTrinczek** [comment]
Hey. I did that but i get the very same error.

**Comment by crispyaus** [comment]
> Hey. I did that but i get the very same error.

You can use my api . https://github.com/JackCrispy/fivem

**Comment by LouisTrinczek** [comment]
> > Hey. I did that but i get the very same error.
> 
> You can use my api . https://github.com/JackCrispy/fivem

Yeah i'm using that now. Do you happen to know if there's any way to get the Server state, so if its Online or Offline into an api or something like that?

**Comment by crispyaus** [comment]
> > > Hey. I did that but i get the very same error.
> > 
> > 
> > You can use my api . https://github.com/JackCrispy/fivem
> 
> Yeah i'm using that now. Do you happen to know if there's any way to get the Server state, so if its Online or Offline into an api or something like that?

Yes. Basically if a server is offline it won’t return anything. So you can setup something if there’s no response in the body, then you can assume it’s offline.

**Comment by jakubiakdev** [comment]
Update: It was easier for me to just fetch players.json and info.json myself
I will still leave this issue open if there will be a fix in the lib :)
